name: Hello2 # ワークフロー名
on: push    # イベント（プッシュ時に起動）
jobs:       # ジョブの定義
  hello:    # ジョブID
    runs-on: ubuntu-latest        # ランナー（Ubuntuで実行） 
    steps:
    - run: echo "Hello, world2"
    - uses: actions/checkout@v6