name: Java
on:
  push:
  #pull_request:                        # プルリクエストが作成されたら起動
  #  paths: ['go/**/*.go']              # ただしGoのファイル変更時のみ
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5      # ステップ1: チェックアウト
      # - uses: actions/setup-go@v5      # ステップ2: 言語セットアップ
      #   with:
      #     go-version: '1.22'
      # - run: go test go/excellent/*.go # ステップ3: テストの実行
      - uses: actions/setup-java@v5      # ステップ2: 言語セットアップ
        with:
          distribution: temurin
          java-version: '21'
          #cache: gradle
      - run: javac java/*.java # ステップ3: コンパイル
      - run: java java/*.java  # ステップ4: 実行
